---
- name: COnfig | Manage configuration.
  ansible.builtin.template:
    force: "{{ taskwarrior_config_file_overwrite }}"
    dest: "{{ taskwarrior_config_file }}"
    src: 'taskrc.j2'
    owner: "{{ taskwarrior_user }}"
    group: "{{ taskwarrior_group }}"
    mode: '0755'
