---
- name: Main | Include variable file.
  ansible.builtin.include_vars:
    file: "./defaults/{{ ansible_distribution | lower }}.yml"

- name: Main | Include install tasks.
  ansible.builtin.include_tasks: install.yml

- name: Main | Include configuration tasks.
  ansible.builtin.include_tasks: config.yml
