---
# tasks file for taskwarrior
#
- name: INCLUDE VARIABLE FILE
  ansible.builtin.include_vars:
    file: "./defaults/{{ ansible_distribution|lower }}.yml"
- name: INCLUDE INSTALL TASKS
  ansible.builtin.include_tasks: install.yml
- name: INCLUDE CONFIG TASKS
  ansible.builtin.include_tasks: config.yml
