---
- name: Converge
  hosts: all
  tasks:
    - ansible.builtin.include_vars:
        file: "./variables.yml"
    - name: "Include spreadcat.taskwarrior"
      ansible.builtin.include_role:
        name: "spreadcat.taskwarrior"
